version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: kevin
      POSTGRES_PASSWORD: kevin
    ports:
      - "5432:5432"
    volumes:
      - C:/Users/progr/Documents/integradora/PostgresSql:/var/lib/postgresql/data