version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: kevin
      POSTGRES_PASSWORD: ale
    ports:
      - "5432:5432"
    volumes:
      - D:/Dessarrollo/PostgresSql:/var/lib/postgresql/data
