version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecomerceejemplo
      POSTGRES_USER: alexander
      POSTGRES_PASSWORD: 995410
    ports:
      - "5432:5432"
    volumes:
      - /home/ubuntu/postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "4000:4000"
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
